#ifndef __GOL_CONFIG_HPP__
#define __GOL_CONFIG_HPP__

#define CONFIG_WINDOW_WIDTH 1700
#define CONFIG_WINDOW_HEIGHT 1100
#define CONFIG_WINDOW_LEGEND_HEIGHT 0
#define CONFIG_WINDOW_FPS_LIMIT 30

#define CONFIG_CELL_SCALE_FACTOR 2
#define CONFIG_CELL_INIT_TRUE_PROBABILITY 0.055

#endif