#ifndef __GOL_CONFIG_HPP__
#define __GOL_CONFIG_HPP__

#define CONFIG_WINDOW_WIDTH 1600
#define CONFIG_WINDOW_HEIGHT 1200
#define CONFIG_WINDOW_LEGEND_HEIGHT 0
#define CONFIG_SCALE_FACTOR 4

#define CONFIG_CELL_INIT_TRUE_PROBABILITY 0.05

#endif